package com.oyariyders.driver.ui.theme

import androidx.compose.ui.text.googlefonts.GoogleFont
import com.oyariyders.driver.R
// Define the provider object globally
val fontProvider = GoogleFont.Provider(
    providerAuthority = "com.google.android.gms.fonts",
    providerPackage = "com.google.android.gms",
    // Ensure you have an XML file defining the font certificates (usually generated by Android Studio)
    certificates = R.array.com_google_android_gms_fonts_certs
)